version: 0.2

phases:
  install:
    runtime-versions:
      docker: 20
    commands:
      - echo "Installing dependencies..."
      - echo "Logging in to Amazon ECR..."
      - aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 011528265508.dkr.ecr.ap-south-1.amazonaws.com

  pre_build:
    commands:
      - echo "Starting pre-build phase..."
      - REPOSITORY_URI=011528265508.dkr.ecr.ap-south-1.amazonaws.com/ravikant
      - echo "ECR Repository URI: $REPOSITORY_URI"

  build:
    commands:
      - echo "Building Docker image..."
      - docker build -t ravikant .
      - echo "Tagging Docker image..."
      - docker tag ravikant:latest $REPOSITORY_URI:latest

  post_build:
    commands:
      - echo "Pushing Docker image to ECR..."
      - docker push $REPOSITORY_URI:latest
      - echo "Docker image pushed successfully."

artifacts:
  files:
    - '**/*'
  discard-paths: yes
